# Generated by Django 4.1.5 on 2023-01-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Номер телефона')),
                ('amo_url', models.CharField(blank=True, max_length=50, verbose_name='Адрес AmoCrm')),
                ('access_token', models.CharField(blank=True, max_length=200, verbose_name='Access token')),
                ('refresh_token', models.CharField(blank=True, max_length=200, verbose_name='Refresh token')),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='App Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=200, verbose_name='App Client Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
