# Generated by Django 4.1.5 on 2023-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0002_client_auth_code_alter_client_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth_code',
            field=models.CharField(blank=True, max_length=2000, verbose_name='App AuthCode'),
        ),
    ]
